### ISSUE TITLE
Color leaked when items overflowed

### ISSUE THREAD

**Issue by Huxpro** [pcwalton/vscode-powerline#3]
First of all, love this "extension"! 

I noticed a weird bug that when items overflowed the window, the VIM status color would leak out and swallow the middle item that is being folded up. I recorded a video to make the scenario clear and (hopefully) reproducible to you:

https://user-images.githubusercontent.com/5563315/113543730-da4ed100-959b-11eb-9f2a-9ef366ce084d.mov

As you can see, I tried to debug it but CSS is awesome :)

**Comment by pcwalton** [comment]
Thanks! This is a duplicate of #2
